[project]
name = "deku-bot"
version = "1.0.0"
description = "Instagram va Pinterest yuklab beruvchi Telegram bot"
requires-python = ">=3.10,<3.13"
dependencies = [
    "aiogram==3.4.1",
    "Flask==3.0.3",
    "requests==2.32.3",
    "gunicorn==22.0.0"
]
